version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8010:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./server:/var/www/:delegated
    depends_on:
      - php

  php:
    container_name: php-laravel
    build: ./docker/php
    volumes:
      - ./server:/var/www/:delegated

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Taipei
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    ports:
      - 3306:3306