services:
  nginx:
    image: nginx:latest
    ports:
      - 8010:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./server:/var/www/:delegated
    depends_on:
      - php

  php:
    container_name: php-laravel
    build: ./docker/php
    volumes:
      - ./server:/var/www/:delegated
